cart/urls.py
from django.urls import path
from .views import addToCart, viewCart, removeFromCart, updateCartItemQuantity

urlpatterns = [
    path('addToCart/<int:id>-<int:quantity>/', addToCart, name='addToCart'),
    path('', viewCart, name='viewCart'),
    path('removeFromCart/<int:id>/', removeFromCart, name='removeFromCart'),
    path('updateCart/<int:id>-<int:quantity>/', updateCartItemQuantity, name='updateCartItemQuantity'),
]

online_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('account/', include('account.urls')),
    path('product/', include('product.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
]

urlpatterns += staticfiles_urlpatterns()

order/urls.py
from django.urls import path
from .views import displayOrders, changeOrderConfirmation, confirmOrder

urlpatterns = [
    path('display-orders/', displayOrders, name='displayOrders'),
    path('change-order-confirmation/<int:id>', changeOrderConfirmation, name='changeOrderConfirmation'),
    path('confirmOrder/', confirmOrder, name='confirmOrder')
]

order/models.py
from django.db import models
from product.models import Product
from .infrastructure.modeldate import ModelDate

# Create your models here.
class DeliveryAddress(models.Model):
    """
    Stores a delivery address of the order.
    """
    firstName = models.CharField(max_length=150, blank=False, help_text="First name of a purchaser.")
    lastName = models.CharField(max_length=150, blank=False, help_text="Last name of a purchaser.")
    email = models.EmailField(blank=False, help_text="E-mail address of a purchaser. An order confirmation is sent to this e-mail address.")

class Order(ModelDate):
    """
    Represents a user order.
    """
    deliveryAddress = models.ForeignKey(DeliveryAddress, on_delete=models.DO_NOTHING, help_text="Delivery address of the order.")
    isConfirmed = models.BooleanField(default=False, help_text="Indicates if the order is confirmed.")

class OrderElement(models.Model):
    """
    Represents an order's element
    """
    product = models.ForeignKey(Product, on_delete=models.DO_NOTHING, help_text="Order element.")
    quantity = models.IntegerField(help_text="Quantity of elements.")
    order = models.ForeignKey(Order, on_delete=models.DO_NOTHING, help_text="Associated order.")

order/forms.py
from django.forms import ModelForm
from django import forms
from .models import DeliveryAddress

class DeliveryAddressForm(ModelForm):
    class Meta:
        model = DeliveryAddress
        fields = ['firstName', 'lastName', 'email']
        labels = {
            'firstName': 'Name',
            'lastName': 'Surname',
            'email': 'E-mail'
        }
        widgets = {
            'firstName': forms.TextInput(attrs={ 'class': 'form-control mb-2'}),
            'lastName': forms.TextInput(attrs={ 'class': 'form-control mb-2'}),
            'email': forms.TextInput(attrs={ 'class': 'form-control mb-4', 'type': 'email'})
        }

order/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.core.mail import send_mail, EmailMultiAlternatives
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.conf import settings
from .models import Order, DeliveryAddress, OrderElement
from .forms import DeliveryAddressForm
from product.models import Product

# Create your views here.
@login_required(login_url='login')
def displayOrders(request):
    """
    Displays each order confirmed by users.

    **Context**

    ``orders``
        All orders confirmed by users.

    **Template:**

    If user is staff then returns :template:`order/orders.html`.
    If user is not staff then redirets to the index endpoint.
    """
    if request.user.is_staff:
        orders = Order.objects.all()
        context = {'orders': orders}
        return render(request, 'order/orders.html', context)
    else:
        messages.add_message(request, messages.ERROR , 'Insufficient authorization')
        return redirect('index')

@login_required(login_url='login')
def changeOrderConfirmation(request, id):
    """
    Change the confirmation state of the order with the specified id.

    **Template:**

    If user is staff then redirects displayOrders endpoint.
    If user is not staff then redirets to the index endpoint.
    """
    if request.user.is_staff:
        order = get_object_or_404(Order, id = id)
        order.isConfirmed = not order.isConfirmed
        order.save()
        return redirect('displayOrders')
    else:
        messages.add_message(request, messages.ERROR , 'Insufficient authorization')
        return redirect('index')

@login_required(login_url='login')
def confirmOrder(request):
    """
    Confirms users orders.

    **Template:**

    If the confirmation is success then redirects to the index endpoint.
    If the confirmation is not succes then redirect to the cart endpoint.
    """
    if request.method == 'POST':
        if request.session.has_key('cartItems'):
            sessionCartItems = request.session['cartItems']
            if len(sessionCartItems) > 0:
                form = DeliveryAddressForm(request.POST)
                if form.is_valid():
                    firstName = form.cleaned_data['firstName']
                    lastName = form.cleaned_data['lastName']
                    email = form.cleaned_data['email']
                    deliveryAddress = DeliveryAddress(firstName = firstName, lastName = lastName, email = email)
                    deliveryAddress.save()
                    order = Order(deliveryAddress = deliveryAddress)
                    order.save()
                    orderPrice = 0
                    for cartItem in sessionCartItems:
                        product = get_object_or_404(Product, id = cartItem['id'])
                        orderPrice = orderPrice + (product.Price * cartItem['quantity'])
                        orderElement = OrderElement(product = product, quantity = cartItem['quantity'], order = order)
                        orderElement.save()
                    context={"firstName": firstName, "orderPrice": orderPrice, "orderId": order.id}
                    htmlContent = render_to_string("email.html", context)
                    textContent = strip_tags(htmlContent)
                    email = EmailMultiAlternatives(
                        "Order confirmation",
                        textContent,
                        settings.EMAIL_HOST_USER,
                        [email]
                    )
                    email.send()
                    messages.add_message(request, messages.SUCCESS, 'Order has been accepted')
                    del request.session['cartItems']
                    return redirect('index')
    
    return redirect('viewCart')

templates/order/orders.html
{% extends "template.html" %}

{% block content %}
<section style="margin-top:10%">
    {% if orders|length > 0 %}
    <div class="table-responsive-xxl">
        <table class="table table-bordered text-center" style="margin-top:10%">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Delivery Address</th>
                    <th scope="col">Order Elements</th>
                    <th scope="col">Total Price</th>
                    <th scope="col">Modification</th>
                    <th scope="col">Creation</th>
                    <th scope="col">Confirmation</th>
                </tr>
            </thead>
            <tbody>
                {% for order in orders %}
                    <tr>
                        <th scope="row">{{order.id}}</th>
                        <td>
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th scoppe="col">Name</th>
                                        <th scoppe="col">Surname</th>
                                        <th scoppe="col">E-mail</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>{{order.deliveryAddress.firstName}}</td>
                                        <td>{{order.deliveryAddress.lastName}}</td>
                                        <td>{{order.deliveryAddress.email}}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </td>
                        <td>
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th scoppe="col">Id</th>
                                        <th scoppe="col">Name</th>
                                        <th scoppe="col">Price</th>
                                        <th scoppe="col">Quantity</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for orderElement in order|getSetFromManyToOneRelationship:'orderelement_set' %}
                                    <tr>
                                        <th scope="row">{{orderElement.product.id}}</td>
                                        <td>{{orderElement.product.Name}}</td>
                                        <td>{{orderElement.product.Price}}$</td>
                                        <td>{{orderElement.quantity}}</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </td>
                        <td>{{order|calculateTotalOrderPrice}}$</td>
                        <td>
                            {{order.updated_at|date:"H:i"}}<br>
                            {{order.updated_at|date:"d M Y"}}
                        </td>
                        <td>
                            {{order.created_at|date:"H:i"}}<br>
                            {{order.created_at|date:"d M Y"}}
                        </td>
                        <td>
                            {% if order.isConfirmed %}
                            <span class="rounded text-light bg-success d-block mb-1">Confirmed</span>
                            <a class="btn btn-danger" href="{% url 'changeOrderConfirmation' order.id %}">Cancel</a>
                            {% else %}
                            <span class="rounded text-light bg-danger d-block mb-1">Not Confirmed</span>
                            <a class="btn btn-success" href="{% url 'changeOrderConfirmation' order.id %}">Confirm</a>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% else %}
    <div class="text-center">
        <h1 class="mb-5">Lack of the orders in the system</h1>
        <a type="button" class="btn btn-primary" href="{% url 'index' %}">Main page</a>
    </div>
    {% endif %}
</section>
{% endblock %}